"""add multi-tenant tutor tables

Revision ID: 70eca5e03450
Revises: 20260605_baseline
Create Date: 2026-06-05

Adds the Kotobaseed multi-tenant tutor platform tables on top of the
existing CompInput schema. None of the existing tables are touched.

New tables:
  - tutor: per-tenant tutor profile (subdomain slug, plan, classroom quota,
    Stripe Connect, custom domain)
  - tutor_marketplace_profile: opt-in marketplace visibility + intro media
  - student_enrollment: per-tenant student relationship
  - tutor_verification: language credential / teaching credential / identity
    verification with admin review queue
  - theme + tutor_branding: per-tutor theme choice + color/logo
  - tutor_page_section: landing-page builder section list
  - tutor_minute_usage_log: per-day classroom minute ledger
  - platform_subscription: Pro-plan Stripe Subscription on the platform's
    own Stripe account (separate from tutor's Connect account)
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "70eca5e03450"
down_revision: str | None = "20260605_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('css_class_prefix', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('primary_palette_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typography_pair_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_is_active'), 'theme', ['is_active'], unique=False)
    op.create_index(op.f('ix_theme_key'), 'theme', ['key'], unique=True)
    op.create_table('tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tutor_slug', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('languages_taught', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('languages_spoken', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cefr_level_lowest', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('cefr_level_highest', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('public_reply_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('plan', sa.Enum('STARTER', 'PRO', name='tutorplan'), nullable=False),
    sa.Column('plan_started_at', sa.DateTime(), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'PAUSED_DORMANT', 'PAUSED_BILLING', 'SUSPENDED', name='tutoraccountstatus'), nullable=False),
    sa.Column('paused_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_completed_lesson_at', sa.DateTime(), nullable=True),
    sa.Column('classroom_minutes_quota', sa.Integer(), nullable=False),
    sa.Column('classroom_minutes_used_this_cycle', sa.Integer(), nullable=False),
    sa.Column('cycle_started_at', sa.DateTime(), nullable=True),
    sa.Column('overage_policy', sa.Enum('BLOCK', 'AUTO_BILL', name='overagepolicy'), nullable=False),
    sa.Column('stripe_connect_account_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('stripe_platform_customer_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('custom_domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_account_status'), 'tutor', ['account_status'], unique=False)
    op.create_index(op.f('ix_tutor_custom_domain'), 'tutor', ['custom_domain'], unique=True)
    op.create_index(op.f('ix_tutor_plan'), 'tutor', ['plan'], unique=False)
    op.create_index(op.f('ix_tutor_stripe_connect_account_id'), 'tutor', ['stripe_connect_account_id'], unique=False)
    op.create_index(op.f('ix_tutor_tutor_slug'), 'tutor', ['tutor_slug'], unique=True)
    op.create_index(op.f('ix_tutor_user_id'), 'tutor', ['user_id'], unique=True)
    op.create_table('platform_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('plan', sa.Enum('STARTER', 'PRO', name='tutorplan'), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_subscription_status'), 'platform_subscription', ['status'], unique=False)
    op.create_index(op.f('ix_platform_subscription_stripe_subscription_id'), 'platform_subscription', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_platform_subscription_tutor_id'), 'platform_subscription', ['tutor_id'], unique=True)
    op.create_table('student_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='studentenrollmentstatus'), nullable=False),
    sa.Column('first_enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_enrollment_status'), 'student_enrollment', ['status'], unique=False)
    op.create_index(op.f('ix_student_enrollment_student_user_id'), 'student_enrollment', ['student_user_id'], unique=False)
    op.create_index(op.f('ix_student_enrollment_tutor_id'), 'student_enrollment', ['tutor_id'], unique=False)
    op.create_table('tutor_branding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('accent_color', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('favicon_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('cefr_glyphs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_branding_theme_id'), 'tutor_branding', ['theme_id'], unique=False)
    op.create_index(op.f('ix_tutor_branding_tutor_id'), 'tutor_branding', ['tutor_id'], unique=True)
    op.create_table('tutor_marketplace_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_enabled', sa.Boolean(), nullable=False),
    sa.Column('intro_video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sample_videos_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_marketplace_profile_marketplace_enabled'), 'tutor_marketplace_profile', ['marketplace_enabled'], unique=False)
    op.create_index(op.f('ix_tutor_marketplace_profile_tutor_id'), 'tutor_marketplace_profile', ['tutor_id'], unique=True)
    op.create_table('tutor_minute_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=False),
    sa.Column('minutes_used', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_minute_usage_log_tutor_id'), 'tutor_minute_usage_log', ['tutor_id'], unique=False)
    op.create_index(op.f('ix_tutor_minute_usage_log_usage_date'), 'tutor_minute_usage_log', ['usage_date'], unique=False)
    op.create_table('tutor_page_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.Enum('HERO_PORTRAIT', 'FEATURES_GRID', 'LEVELS_ALPHABET', 'PRICING_GRID', 'ABOUT_PORTRAIT', 'REVIEWS_GRID', 'FAQ_ACCORDION', 'VIDEO_EMBED', 'CTA_BAND', 'LANGUAGE_INTRO', name='tutorpagesectiontype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('content_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_page_section_position'), 'tutor_page_section', ['position'], unique=False)
    op.create_index(op.f('ix_tutor_page_section_tutor_id'), 'tutor_page_section', ['tutor_id'], unique=False)
    op.create_table('tutor_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('LANGUAGE_PROFICIENCY', 'TEACHING_CREDENTIAL', 'IDENTITY', name='tutorverificationkind'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('evidence_file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_verification_kind'), 'tutor_verification', ['kind'], unique=False)
    op.create_index(op.f('ix_tutor_verification_status'), 'tutor_verification', ['status'], unique=False)
    op.create_index(op.f('ix_tutor_verification_tutor_id'), 'tutor_verification', ['tutor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('platform_subscription')
    op.drop_table('tutor_minute_usage_log')
    op.drop_table('tutor_page_section')
    op.drop_table('tutor_branding')
    op.drop_table('theme')
    op.drop_table('tutor_verification')
    op.drop_table('student_enrollment')
    op.drop_table('tutor_marketplace_profile')
    op.drop_table('tutor')
